name: LegionOfSins
main: me.waternode.server.legion.of.sins.LOSMain
version: 1.4
author: WaterNode
description: The Legion of Sins plugin!

commands:
  gener:
    description: Information for your game.